title: Impact Mapping
description: Impact Mapping community web site
copyright: > 
  Copyright &copy; Neuri Consulting LLP.
  Except where otherwise noted, the content in this site is 
  licensed under <a href="http://creativecommons.org/licenses/by/4.0/legalcode">
  Creative Commons Attribution 4.0 International License
  </a>, and available from 
  <a href="https://github.com/impactmapping/www.impactmapping.org">GitHub</a>.

